name: test
on:
  push:
      branches-ignore:
        - 'main'
      tags-ignore:
        - '**'

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    name: Build & Test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.x
      - name: use cache
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: test
        run: go test -race -cover ./...

      - name: prepare install test
        run: |
          echo 'image: {{ tfstate "docker_image.ubuntu.name" }}' > input.yaml
      - name: run composite action
        uses: ./
        with:
          input: input.yaml
          output: output.yaml
          tfstate: cmd/testdata/terraform.tfstate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: test output
        run: |
          diff output.yaml <(echo "image: ubuntu:latest")
